### ISSUE TITLE
Should accept application/hal+json as response content type

### ISSUE THREAD

**Issue by christianz** [eoin55/HoneyBear.HalClient#1]
Hi, and thanks for a great HAL library.

Some APIs only return content with Content-Type: application/hal+json. Trying to consume these with HalClient fails, as this software only seems to accept application/json.

A fix for this would be to let the HalClient instantiation accept a System.Net.Http.Formatters.MediaTypeFormatter as a constructor parameter and use this for all serialization/deserialization for the current session.

I have some snippets that would allow for this, but would like to hear your thoughts on this before I proceed.

**Comment by eoin55** [comment]
Hi Christian,

Thanks for getting in touch.  It's nice to hear from someone using it in anger :)

I'll take a look at this issue over the weekend.  It shouldn't be a problem to fix it.

If you have any other issues or suggestions, just let me know.

Cheers,
Eoin

**Comment by eoin55** [comment]
Hi @christianz,

I've added support for application/hal+json.  I tested on my own sample API and it seems to work fine.  This is available from v1.0.29.

I didn't add the ability to specify the MediaTypeFormatter as a constructor parameter as I can't think of any other content types that might need to be supported.

If you have any other issues or suggestions, just let me know.  All feedback is welcome :)

Cheers,
Eoin

**Comment by christianz** [comment]
Hi!

Great work, thank you.

The other reason I want to specify my own MediaTypeFormatter is because the API I'm consuming doesn't accept dates in the format serialized by the default formatter. I'd also like to convert property names to lower camel case on serialization, but that's a minor issue (I can change my property names manually if need be).

The date thing might be a weakness in the API I'm using, but it would still be nice to circumvent this weakness by just passing in a custom MediaTypeFormatter.

This is the code I have currently:

    public class HalJsonMediaTypeFormatter : JsonMediaTypeFormatter
    {
        public HalJsonMediaTypeFormatter()
        {
            var serializerSettings = new JsonSerializerSettings();
            serializerSettings.ContractResolver = new LowerCamelCaseContractResolver();
            serializerSettings.NullValueHandling = NullValueHandling.Ignore;
            serializerSettings.Converters.Add(new DumbDateTimeConverter());

            SerializerSettings = serializerSettings;

            SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/hal+json"));
        }
    }

    /// <summary>
    /// Converts property names to lower camel case.
    /// </summary>
    public class LowerCamelCaseContractResolver : DefaultContractResolver
    {
        protected override string ResolvePropertyName(string propertyName)
        {
            var propName = propertyName.ToCharArray();
            var firstChar = char.ToLower(propName[0]);

            return firstChar + propertyName.Substring(1);
        }
    }

    class DumbDateTimeConverter : DateTimeConverterBase
    {
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            var dtVal = (DateTime)value;

            writer.WriteValue(dtVal.ToString("yyyy-MM-dd"));
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            return DateTime.ParseExact(existingValue.ToString(), "yyyy-MM-dd", null);
        }
    }

What do you think?

Christian

**Comment by eoin55** [comment]
Hi @christianz,

Yep, I think that's a valid usage.  I hadn't considered it.

I've overloaded the HalClient constructor, so that now you can pass in a list of MediaTypeFormatters.  By default it will use the HalJsonMediaTypeFormatter.

This is available in v1.0.34.

Let me know how you get on.

Cheers,
Eoin

**Comment by christianz** [comment]
Excellent! I see you've also updated the nuget package. This makes my life a whole lot easier :-)
