### ISSUE TITLE
How do I access nested Links?

### ISSUE THREAD

**Issue by simmotech** [eoin55/HoneyBear.HalClient#15]
Please help!

I cannot work out what I am supposed to do to get at nested Resources.

This code works
`var allLocationLinks = halClient.Root().Get("visibleLocations").Item<AllLocations>().Data;`
and returns 1000+ Locations with ID and Name but but I can't work out how to get at the Links to add the Advisers.

Cheers
Simon

Root JSON
```
{
  "_links": {
    "transactionMappingHierarchy": {
      "href": "https://XXX/nbs/transactionMappingHierarchy"
    },
    "accountByAccountNumber": {
      "href": "https://XXX/nbs/accounts/{accountNumber}",
      "templated": true
    },
    "accountByAccountId": {
      "href": "https://XXX/nbs/accounts/ids/{accountId}",
      "templated": true
    },
    "client": {
      "href": "https://XXX/nbs/clients/{clntId}",
      "templated": true
    },
    "visibleLocations": {
      "href": "https://XXX/nbs/locations"
    },
    "docs": {
      "href": "https://XXX/docs"
    }
  }
}

JSON from visibleLocations
{
  "locations": [
    {
      "locationId": 40000003,
      "name": "1000 IFA Firm 40000003 Ltd",
      "_links": {
        "self": {
          "href": "https://XXX/nbs/locations/40000003"
        },
        "advisers": {
          "href": "https://XXX/nbs/locations/40000003/advisers"
        }
      }
    },
    {
      "locationId": 100002441,
      "name": "10000 IFA Firm 100002441 Ltd",
      "_links": {
        "self": {
          "href": "https://XXX/nbs/locations/100002441"
        },
        "advisers": {
          "href": "https://XXX/nbs/locations/100002441/advisers"
        }
      }
    }, ...etc...

```
My POCO classes

```
	public class AllLocations
	{
		public Location[] Locations { get; set; }
	}

	public class Location
	{
		[JsonProperty("locationId")]
		public int ID { get; set; }

		public string Name { get; set; }

		[JsonProperty("advisers")]
		public Adviser[] Advisers { get; set; }
	}

	public class Adviser
	{
		[JsonProperty("adviserID")]
		public int ID { get; set; }

		public string Forename { get; set; }

		public string Surname { get; set; }

		[JsonProperty("adviserOutletID")]
		public int OutletID { get; set; }
	}

```

**Comment by eoin55** [comment]
Hi Simon,

Thanks for getting in touch.

I think the reason it's not working is because _visibleLocations_ isn't a HAL resource.  I wouldn't expect _HalClient_ to work in this scenario.

I also ran your JSON through the [HAL browser](https://github.com/mikekelly/hal-browser) and it didn't seem to respect it either.

Can I suggest that you convert your locations array to a HAL resource and embed the array of location resources.  I tried this by modifying your JSON and the following worked for me.  (Note: I'm using static JSON files, hence the file extensions.)

```
{
  "_links": {
    "self": { "href": "http://localhost/locations.json" }
  },
  "_embedded": {
    "locations": [
      {
        "locationId": 40000003,
        "name": "1000 IFA Firm 40000003 Ltd",
        "_links": {
          "self": {
            "href": "http://localhost/locations-40000003.json"
          },
          "advisers": {
            "href": "http://localhost/locations-40000003-advisers.json"
          }
        }
      },
      {
        "locationId": 100002441,
        "name": "10000 IFA Firm 100002441 Ltd",
        "_links": {
          "self": {
            "href": "http://localhost/locations-100002441.json"
          },
          "advisers": {
            "href": "http://localhost/locations-100002441-advisers.json"
          }
        }
      }
    ]
  }
}
```
...and the C# code:
```
var http = new HttpClient {BaseAddress = new Uri("http://localhost/root.json")};
var halClient = new HalClient(http);

var locations =
    halClient
        .Root()
        .Get("visibleLocations")
        .Get("locations")
        .Items<Location>();
foreach (var location in locations)
{
    var adviser =
        halClient
            .Get(location, "advisers")
            .Item<Adviser>()
            .Data;

    // Do something with this adviser...
}
```

I hope this helps.  Give me a shout if you have any questions.

Cheers,
Eoin

**Comment by simmotech** [comment]
Hi Eoin

 

Thanks for the response.  

You have to forgive my ignorance here – I am on a very steep learning curve as JSON, HAL, HTTPClient are all new to me as of this week!

 

The JSON is not mine so I can’t change it at all – it is from a Financial Services supplier in the UK so I have to use what I am given.

 

You mention using a “HAL resource”. I am not quite sure what you mean by that but since my post, I have added this to my Location POCO:

 

              [JsonProperty("_links")]

              public Dictionary<string, IResource> Links;

 

and it appears to get populated so I just started playing with that to see what I can get from it.

 

By “HAL resource”, do you recommend using a base class for Links (and anything else common) and have my POCOs derive from that?

 

Cheers

Simon

**Comment by eoin55** [comment]
Hi Simon,

That's a cool solution.  I hadn't considered that approach.

Also, I didn't realise that you don't own the API.  By exposing _locations_ as a plain array, I don't believe they're strictly adhering to HAL.  (However, I could be wrong.  This is just my opinion.)

I think what you have is fine; POCOs should work fine for you.  Something like this may also work (although you'll probably need to add _links_ to your _Location_ POCO):

```
var locations =
    halClient
        .Root()
        .Get("visibleLocations")
        .Item<AllLocations>()
        .Data;
foreach (var location in locations.Locations)
{
    var advisers =
        halClient
            .Root(location.Href)
            .Get("advisers")
            .Item<Adviser>()
            .Data;
}
```

Let me know if you have any questions.

Cheers,
Eoin

**Comment by simmotech** [comment]
Typical! My first go with this HAL stuff and I might be dealing with non-standard data. :-)

The code you mention is vaguely how I expected it to work but all Hrefs I look at appear to be null - presumably because of the JSON array issue you mention.

The JSON I included originally truncated the locations object - it does have this at the end:-
`  "_links": {
    "docs": {
      "href": "https://XXX/nbs/docs/locations"
    }
  }
`
Maybe I can somehow fudge things (I have your source code) so a "self" property gets added to the _links with its HRef set to the current url.

**Comment by simmotech** [comment]
Hi Eoin

 

I have a number of questions (and possibly suggestions – though since they depend on my current understanding may be rubbish!).

Is it OK to post them here or would you prefer private email (or prefer for me to just go away :-) )?

 

Cheers

Simon

**Comment by eoin55** [comment]
Hi Simon,

Sure, no problem.  Just email me at _eoin55_ (at) _gmail.com_

Cheers,
Eoin

**Comment by codingbadger** [comment]
@simmotech Would you mind contacting me about this - I almost certain that I am in the process of starting to use the very same API and would appreciate any information to help me out. My email is barry [at]  codingbadger [dot] com
