### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by dmunch** [eoin55/HoneyBear.HalClient#18]
Hi,

and thanks again for this great library, the fluent interface really is fun to use!

While using the first time I kind of expected the library to fully support async/await and was surprised it didn't. I figured this might be a nice excersice, so I went ahead trying to implement it. 

Turns out going async and keeping the fluent interface wasn't straight-forward.  The resulting pull-request (which I didn't send in yet, since it depends on https://github.com/eoin55/HoneyBear.HalClient/pull/17) refactors quite a bit in the code, as such I understand you might hesitate merging or even question the approach taken.

Outlining it roughly:
- `HalClient` is immutable, i.e. all the calls return a new copy with the new state
- Most of the methods are extension methods operating on `IHalClient`, allowing easy chaining of `Task<IHalClient>`'s.

While the changes in the implementation are rather important, fortunately the tests behaved pretty nicely and only needed some slight changes, mainly for the immutable part. Also, adding tests for the async methods was as easy as copying the existing ones and only changing the sync method calls to the async method calls. Kudos!

You can find call the changes on this branch:
https://github.com/dmunch/HoneyBear.HalClient/tree/dmunch-async

If you decide to accept merging those changes there's a tiny list of things yet to be done. Of course I'd happily take care of these.

- [ ] Add POST
- [ ] Add PUT
- [ ] Add PATCH
- [ ] Add DELETE
- [ ] Adjust documentation

**Comment by eoin55** [comment]
Hi @dmunch,

Again, sorry for the slow response.  I've create a pull request to introduce your _immutable_ suggestion: #19.

Could you take a look, please?

Then I'll add the async stuff in a separate PR.  For simplicity's sake, I didn't want to do it all in the one go.

Thanks,
Eoin

**Comment by dmunch** [comment]
Hi @eoin55, 

no worries for the delay, I'm glad you consider integrating my changes!

The immutable PR looks fine, as I've seen you even already merged it. Great! Once the PR for the async stuff is made (I can do the rebasing etc. if you want me to), I'll add the remaining missing points listed above to the PR. 

Best,
Daniel

**Comment by eoin55** [comment]
Hi @dmunch,

Sorry again for the delay.  I've created PR #20 with the async extensions.

Could you take a look, please?

Cheers,
Eoin

**Comment by daniel-munch-cko** [comment]
Same pic, same person, new job, new handle. No worries for the delay, no urgency on this side. I just took a look, see the comments on the PR. 

Best,
Daniel

**Comment by eoin55** [comment]
Feature added in version 2.1.
