### ISSUE TITLE
Add support for HAL links retrieval

### ISSUE THREAD

**Issue by dmitrynovik** [eoin55/HoneyBear.HalClient#21]
It took me some time to figure out how the access the links. The documentation is lacking an example(s).

**Comment by eoin55** [comment]
Hi @dmitrynovik,

Thanks for the feedback.  I'll add some documentation soon.

Why do you need access to the Links?  One of the goals of this library is to abstract the HAL semantics from the user/client.  I'm interested to hear how people are using it.

Thanks,
Eoin

**Comment by dmitrynovik** [comment]
The links is the core of HAL: given a resource, they list the related resouces I can navigate to.

As I can see, the Links are already  a propery on IResource<T>. All IMO is needed is to add a few lines of documentation to Readme.md

**Comment by eoin55** [comment]
Hi @dmitrynovik,

Thanks for the feedback.  I've updated the README.md.

I'm closing this issue now, but let me know if you have any other suggestions.

Eoin
