### ISSUE TITLE
Be able to specify which MediaTypeFormatter to use when PUT or POSTing

### ISSUE THREAD

**Issue by christianz** [eoin55/HoneyBear.HalClient#3]
Hi!

I downloaded the latest version of the nuget package, and everything seems to work fine when fetching data from the API. But I'm still not able to specify the serializer settings when POSTing to the API. 

In JsonHttpClient, these lines should also take in a MediaTypeFormatter:

```cs
public Task<HttpResponseMessage> PostAsync<T>(string uri, T value)
  => HttpClient.PostAsync(uri, value, _mediaTypeFormatter);

public Task<HttpResponseMessage> PutAsync<T>(string uri, T value)
  => HttpClient.PutAsync(uri, value, _mediaTypeFormatter);
```

I'm not sure what the best strategy is to use here. I see that you allow a collection of MediaTypeFormatters to be passed into the HalClient constructor. But we can only specify a single formatter when serializing objects. Should it instantiate the JsonHttpClient with the First() available MediaTypeFormatter?

Christian

**Comment by eoin55** [comment]
Hi @christianz,

Thanks again for the suggestions.  I took a slightly different approach, but hopefully you should be able to achieve the same result.

From v1.0.38 onwards, you should be able to provide your own implementation of `IJsonHttpClient`.  In your implementation, you can specify whichever `MediaTypeFormatter` you need.

Hopefully this approach should give you more control over how the HTTP requests are handled, while still leaving the HAL specific stuff to `HalClient`.

Let me know what you think.

Cheers,
Eoin
