### ISSUE TITLE
Support for .NET 4.5

### ISSUE THREAD

**Issue by bobhonores** [eoin55/HoneyBear.HalClient#5]
Hi, 

I really like this fluent API. It'll be nice to have support for .NET 4.5 and above, instead only limited to 4.5.2.

Thanks.

Regards,

Roberto

**Comment by eoin55** [comment]
Hi Roberto,

Great!  Thanks for the positive feedback.

Yep, that's a good suggestion. I'll try to take a look this weekend.

Cheers,
Eoin

**Comment by eoin55** [comment]
Support added in version 1.0.50.
