### ISSUE TITLE
NUnit 2.6.4 in VS2015

### ISSUE THREAD

**Issue by berhir** [eoin55/HoneyBear.HalClient#7]
Hi, I have started a pull request to allow JsonPropertyAttributes on model classes ( #6 ) but I have problems to run the NUnit tests in Visual Studio 2015.
I can run it with NUnit outside of Visual Studio but some tests fail because the assembly binding redirect of Ploeh.SemanticComparison doesn't work.

I would like to add some tests for this new functionality.
Do you have an idea why it doesn't work?

**Comment by eoin55** [comment]
Hi @berhir,

Your implementation looks good.  Are you using Resharper to run your unit tests in VS2015?  Because it works fine for me.

Unfortunately, I'm going on holiday today and I won't be able to review your PRs until early January.  If this is blocking you, it might be worth forking your changes.  Sorry for the inconvenience.  I'll take a look as soon as I get back.

Cheers,
Eoin

**Comment by berhir** [comment]
Thanks for your feedback!
I don't use Resharper and Visual Studio doesn't show the tests in the Test Explorer.

For the .net standard implementation (#8) I updated NUnit to the latest version and the tests showed up immediately. But the documentation says that version 2.6.2 should support VS2015 too.

I will try to find the problem and will write some tests.

Have a great holiday,
Bernd

**Comment by eoin55** [comment]
Hi @berhir,

Have you tried installing the **NUnit Test Adapter** extension in Visual Studio 2015?  I did and I was able to  execute the tests using the Test Explorer.

It might be best to get #8 merged first before tackling this one.

Cheers,
Eoin

**Comment by berhir** [comment]
Hi @eoin55,

I haven't tried the NUnit Test Adapter yet. I was not aware that the extension is required.
But I also suggest to merge #8 first.

**Comment by eoin55** [comment]
Hi @berhir,

Just wondering if you're still interesting in merging #6?  I think it just needs some test coverage.

If you don't have time, I can take a look at merging your branch.

Thanks,
Eoin

**Comment by berhir** [comment]
Sorry, I worked on another project lately and totally forgot about this pull request.
Yes it's only the test coverage that's missing.

The problem is I already updated my dev PCs to Visual Studio 2017 and the final .net core SDK.
And it's not backward compatible with the old .xproj format.
I tried to update the HalClient but then I noticed that the NUnit tooling is not ready yet (See here: nunit/dotnet-test-nunit#91).

If you have the time you can merge the branch. Or I will take a look after the project is VS2017 ready.

**Comment by eoin55** [comment]
Hi @berhir,

Thanks for getting back to me.  No worries, I'll take a look.

Unfortunately, I'm having the same issues with the latest DotNet Core SDK.  I should be able to fix it this week though.

Eoin

**Comment by eoin55** [comment]
Done as part of PR #12 and release v1.0.97.
